### ISSUE TITLE
Deleting a sponsored Listing isn't working

### ISSUE THREAD

**Issue by andrewb2** [Tradeversity/web-admin-panel#10]
<img width="415" alt="screen shot 2017-08-02 at 11 34 33 am" src="https://user-images.githubusercontent.com/8754135/28881573-92a53caa-7776-11e7-984f-5e15098fb67e.png">

**Comment by zachcb** [comment]
Oh, I know what it is. The confirmation dialog shows up behind the main dialog. Should be a quick fix.

**Comment by zachcb** [comment]
Fixed!
