### ISSUE TITLE
Users tab should default to Flagged Users and empty message should say “There are currently no Flagged Users” instead of “No Data Available”

### ISSUE THREAD

**Issue by andrewb2** [Tradeversity/web-admin-panel#2]
<img width="972" alt="screen shot 2017-08-01 at 1 17 59 pm" src="https://user-images.githubusercontent.com/8754135/28838243-cf99a114-76bd-11e7-8e05-53d000bab980.png">

**Comment by zachcb** [comment]
Added for all pages.
