### ISSUE TITLE
On the Sponsored Listings tab, when I upload a picture it loads for a second then redirects me to the login page with this error

### ISSUE THREAD

**Issue by andrewb2** [Tradeversity/web-admin-panel#3]
<img width="401" alt="screen shot 2017-08-01 at 1 24 04 pm" src="https://user-images.githubusercontent.com/8754135/28838306-fddff28a-76bd-11e7-9688-ea1f7176677f.png">

**Comment by zachcb** [comment]
The cause of this is that your email is not verified. Evan is adding emails now and I am adding an inline error so it doesn't kick you out.

**Comment by zachcb** [comment]
<img width="848" alt="screen shot 2017-08-01 at 2 41 40 pm" src="https://user-images.githubusercontent.com/3999557/28841255-9f48097e-76c7-11e7-9123-5dbc1d194925.png">

It now looks like this. I'm pushing the update now.
