### ISSUE TITLE
Approve/Deny buttons on Flagged Listings page aren't doing anything

### ISSUE THREAD

**Issue by andrewb2** [Tradeversity/web-admin-panel#7]
<img width="437" alt="screen shot 2017-08-01 at 4 44 02 pm" src="https://user-images.githubusercontent.com/8754135/28846230-a6344458-76d8-11e7-870b-6c0d7867d43e.png">

**Comment by zachcb** [comment]
Fixed, need verification from @andrewb2.

**Comment by andrewb2** [comment]
I set a listing as flagged in the database but it is not appearing in the Flagged Listings table @zachcb

**Comment by zachcb** [comment]
What listing ID on what marketplace?

**Comment by andrewb2** [comment]
Listing id is gyPhXFo2Wvz
Marketplace is tradeversity.com

**Comment by andrewb2** [comment]
school id is "KM4jj3bsL7f"

**Comment by zachcb** [comment]
I tried this on multiple posts in multiple marketplaces and haven't been able to reproduce that. I might try to create a new user without verifying the email and see what happens.
