### ISSUE TITLE
Add New Organization should have Organization Name field instead of First Name/Last Name

### ISSUE THREAD

**Issue by andrewb2** [Tradeversity/web-admin-panel#8]
<img width="333" alt="screen shot 2017-08-02 at 11 23 23 am" src="https://user-images.githubusercontent.com/8754135/28881086-0238bb3e-7775-11e7-89fb-1864c2ee8cd4.png">

**Comment by zachcb** [comment]
An organization is a user. A user requires a first and last name. We'd have to change the server in a lot of different ways to change that.

**Comment by andrewb2** [comment]
Could we store Organization Name in the First Name field and leave the Last Name field blank? Or store a space in that field?
